spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/verification?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none
server:
  port: 80
  session:
    timeout: 60

#security:
#  basic:
#    enabled: false
qiquinn:
  security:
    social:
      qq:
        app-id: 101386962
        app-secret: 2a0f820407df400b84a854d054be8b6a
        provider-id: callback.do
      wechat:
        app-id: 101386962
        app-secret: 2a0f820407df400b84a854d054be8b6a
        provider-id: wechat
      filter-processes-url: /qqLogin
    validate:
      phonecode:
        sid: 7202af6405a03c5e3c039570a8952d5f
        token: fd787f94b8bd7dc228e636f716a40251
        app-id: d7a8adf5de354f328856992e1a004c70
        count: 4
        lose-time: 300
        content: 这是短信模板的信息：验证码是
      imagecode:
        width: 200
        height: 50
#        url: /user,/user/*
    browze:
      login-page: /demo-login1.html
      sign-up-url: /demo-regist.html
