spring:
  datasource:
    data-password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/verification?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
  session:
    store-type: none
server:
  port: 8080

#security:
#  basic:
#    enabled: false
qiquinn:
  security:
    validate:
      imagecode:
        width: 500
        height: 500
        url: /user,/user/*
#    browze:
#      login-page: /demo-login1.html